"""Белый список таблиц и колонок, куда пишет конвейер. Имена в SQL берутся только отсюда."""

COLUMNS: dict[str, tuple[str, ...]] = {
    "banks": ("bank", "in_lnr", "presence_format", "scope", "source_url"),
    "infrastructure": (
        "bank",
        "city",
        "offices_full",
        "offices_mfc",
        "offices_mobile",
        "atms",
        "source_url",
    ),
    "products": (
        "bank",
        "product_id",
        "block",
        "product_type",
        "product_name",
        "segment",
        "available_in_lnr",
        "channels",
        "region_method",
        "source_url",
        "notes",
    ),
    "conditions": (
        "bank",
        "product_id",
        "parameter",
        "value",
        "unit",
        "condition",
        "better",
        "region_method",
        "source_type",
        "source_url",
        "evidence",
        "confidence",
        "collected_at",
    ),
    "scenarios": (
        "scenario_id",
        "bank",
        "product_id",
        "program",
        "metric",
        "value",
        "unit",
        "calc_method",
        "assumptions",
        "region_method",
        "source_url",
    ),
    "changes": (
        "prev_snapshot_date",
        "bank",
        "product_id",
        "parameter",
        "old_value",
        "new_value",
        "delta",
        "alert",
    ),
    "gaps": (
        "block",
        "scenario_or_parameter",
        "metric",
        "sber_value",
        "best_bank",
        "best_value",
        "others_median",
        "delta_vs_best",
        "delta_vs_median",
        "status",
        "comment",
    ),
    "data_quality": (
        "bank",
        "block",
        "params_planned",
        "params_collected",
        "not_confirmed",
        "coverage_pct",
        "issues",
    ),
}

RAW_EXTENSIONS = {"html": "html", "pdf": "pdf", "screenshot": "png", "text": "txt"}

# Ключ строки внутри среза. Повторный запуск в ту же дату заменяет строки прежних запусков
# с тем же ключом; дубликат внутри одного запуска — ошибка.
KEYS: dict[str, tuple[str, ...]] = {
    "banks": ("bank",),
    "infrastructure": ("bank", "city"),
    "products": ("product_id",),
    "conditions": ("product_id", "parameter"),
    "scenarios": ("scenario_id", "bank", "program", "metric"),
    "changes": ("bank", "product_id", "parameter"),
    "gaps": ("block", "scenario_or_parameter", "metric"),
    "data_quality": ("bank", "block"),
}
